//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Obuchalkin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Progress
    {
        public int ID { get; set; }
        public string Login { get; set; }
        public string Course { get; set; }
        public string Section { get; set; }
        public Nullable<int> Page { get; set; }
        public bool TestCompleted { get; set; }
    
        public virtual User User { get; set; }
    }
}
